<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_PrincipalAmt</name>
   <tag></tag>
   <elementGuidId>1a66a14c-5bb2-4cc9-9ac2-4884ea7a0c99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name=&quot;06PrincipalPerRepayment&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name=&quot;06PrincipalPerRepayment&quot;]</value>
   </webElementProperties>
</WebElementEntity>
