<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Delete</name>
   <tag></tag>
   <elementGuidId>df3dd181-24c6-4fae-a91d-9139d9f8ff20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name=&quot;Delete&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uitype</name>
      <type>Main</type>
      <value>Button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Delete_3116cd2a3fedd19FZ%28313</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Delete</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-props</name>
      <type>Main</type>
      <value>readOnly:false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>require([&quot;uxp/utility&quot;], function(utility){utility.displayTooltipMessage(&quot;Delete_3116cd2a3fedd19FZ%28313&quot;);});</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>require([&quot;uxp/utility&quot;], function(utility){utility.toolTipHandling();});</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>require([&quot;uxp/events&quot;], function(events){events.eventsToInvoke({&quot;callService&quot;:[&quot;{\&quot;srcFormId\&quot;:\&quot;116cd2a3fedd19FZ%28313\&quot;,\&quot;mandatoryConfig\&quot;:[],\&quot;requestMapping\&quot;:{\&quot;03ProductContextcode\&quot;:\&quot;[\\\&quot;ProductContextCode116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03ISOCurrencyCode\&quot;:\&quot;[\\\&quot;LoanAmount_CurrCode116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;09AmountAsPercentage\&quot;:\&quot;[\\\&quot;ExpressAmountAsPercent116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;06STIAmount\&quot;:\&quot;[\\\&quot;STIAmount116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03Type\&quot;:\&quot;[\\\&quot;Type116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;10SourceVector\&quot;:\&quot;[\\\&quot;disbursementDetails116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03To\&quot;:\&quot;[\\\&quot;To116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03externalPaymentType\&quot;:\&quot;[\\\&quot;paymenttypeHid116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03externalBankCountry\&quot;:\&quot;[\\\&quot;externalCountry116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03DisbursementPayTo\&quot;:\&quot;[\\\&quot;DisbursementPayTo116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03DisbursementAccountID\&quot;:\&quot;[\\\&quot;DisburseAccountID116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;04Date_of_Disbursement\&quot;:\&quot;[\\\&quot;DisbursementDate116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03ThirdPartyMode\&quot;:\&quot;[\\\&quot;ThirdParty_Mode116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;04FinalMaturityDate\&quot;:\&quot;[\\\&quot;FinalMaturityDate116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;06Amount\&quot;:\&quot;[\\\&quot;AmountOrPercentage116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;06intAmountPerDisbursement\&quot;:\&quot;[\\\&quot;fixedInterestAmountPerDisb116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03Mode\&quot;:\&quot;[\\\&quot;Mode116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03LTI_Plan_Type\&quot;:\&quot;[\\\&quot;LTIPlanType116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03externalBeneficiaryAccountId\&quot;:\&quot;[\\\&quot;externalDisburesAccount116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03externalBeneficiaryId\&quot;:\&quot;[\\\&quot;externalBeneficiaryId116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;09LTI_on_OS_Balance\&quot;:\&quot;[\\\&quot;LTIonOsBalance116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03LoanReferenceNumber\&quot;:\&quot;[\\\&quot;LoanReferenceNumber116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03ASTI_Payment_Method\&quot;:\&quot;[\\\&quot;ASTIPaymentMethod116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03ThirdPartyAccountID\&quot;:\&quot;[\\\&quot;ThirdPartyAccountID116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03externalPaymentRef\&quot;:\&quot;[\\\&quot;paymentReference116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03ThirdPartyPayableAt\&quot;:\&quot;[\\\&quot;ThirdPartyPayableAt116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;04FirstRepaymentDate\&quot;:\&quot;[\\\&quot;FirstRepaymentDate116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;06LTIAmount\&quot;:\&quot;[\\\&quot;LTIAmount116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;06LoanAmount\&quot;:\&quot;[\\\&quot;LoanAmount116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;09MultiDisbursement\&quot;:\&quot;[\\\&quot;isMultiDisbursement116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03ActionFlag\&quot;:\&quot;[\\\&quot;DELETE116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;06ASTIAmount\&quot;:\&quot;[\\\&quot;ASTIAmount116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;09Third_Party_Transfer\&quot;:\&quot;[\\\&quot;ThirdPartyTransfer116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;04LastDisbursementDate\&quot;:\&quot;[\\\&quot;LastDisbursementDate116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03STI_Payment_Method\&quot;:\&quot;[\\\&quot;STIPaymentMethod116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03externalPaymentBic\&quot;:\&quot;[\\\&quot;bic116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03externalPaymentScheme\&quot;:\&quot;[\\\&quot;paymentSchemeHid116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03externalBankName\&quot;:\&quot;[\\\&quot;externalBankName116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03externalBeneficiaryName\&quot;:\&quot;[\\\&quot;externalBeneficiaryName116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;06RemainingAmount\&quot;:\&quot;[\\\&quot;RemainingAmount116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03ThirdPartyPayTo\&quot;:\&quot;[\\\&quot;ThirdPartyPayTo116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03LoanReference\&quot;:\&quot;[\\\&quot;LoanReferenceNumber116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;06ThirdPartyAmount\&quot;:\&quot;[\\\&quot;ThirdParty_Amount116cd2a3fedd19FZ%28313\\\&quot;]\&quot;,\&quot;03DisbursementPayableAt\&quot;:\&quot;[\\\&quot;DisbursementPayableAt116cd2a3fedd19FZ%28313\\\&quot;]\&quot;},\&quot;responseMapping\&quot;:{\&quot;intAmountPerDisbursement\&quot;:\&quot;{\\\&quot;fixedInterestAmountPerDisb116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;ThirdPartyMode\&quot;:\&quot;{\\\&quot;ThirdParty_Mode116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;Disbursement_Type\&quot;:\&quot;{\\\&quot;Type116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;DisbursementAccountID\&quot;:\&quot;{\\\&quot;DisburseAccountID116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;DisableSGFlag\&quot;:\&quot;{\\\&quot;DisableSGFlag116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;STI_Amount\&quot;:\&quot;{\\\&quot;STIAmount116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;externalPaymentType\&quot;:\&quot;{\\\&quot;externalPaymentType116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;Disbursement_To\&quot;:\&quot;{\\\&quot;To116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;DisbursementPayableAt\&quot;:\&quot;{\\\&quot;DisbursementPayableAt116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;ASTI_Amount\&quot;:\&quot;{\\\&quot;ASTIAmount116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;STI_Payment_Method\&quot;:\&quot;{\\\&quot;STIPaymentMethod116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;LTI_Plan_Type\&quot;:\&quot;{\\\&quot;hiddenLabelLTIPlanType116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;,\\\&quot;LTIPlanType116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;SGFlag\&quot;:\&quot;{\\\&quot;ScheduleGenerationFlag116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;externalBeneficiaryAccountId\&quot;:\&quot;{\\\&quot;externalDisburesAccount116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;DisbursementPayTo\&quot;:\&quot;{\\\&quot;DisbursementPayTo116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;IsAmountExpressedAsPercentage\&quot;:\&quot;{\\\&quot;ExpressAmountAsPercent116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;externalPaymentCurrency\&quot;:\&quot;{\\\&quot;externalPaymentCurrency116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;,\\\&quot;hiddenLabelexternalPaymentCurrency116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;LTI_on_OS_Balance\&quot;:\&quot;{\\\&quot;LTIonOsBalance116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;Disbursement_Mode\&quot;:\&quot;{\\\&quot;Mode116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;ThirdPartyAccountID\&quot;:\&quot;{\\\&quot;ThirdPartyAccountID116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;RemainingAmount\&quot;:\&quot;{\\\&quot;AmountOrPercentage116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;,\\\&quot;RemainingAmount116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;externalBankName\&quot;:\&quot;{\\\&quot;externalBankName116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;isExternal\&quot;:\&quot;{\\\&quot;isExternal116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;ThirdPartyAmount\&quot;:\&quot;{\\\&quot;ThirdParty_Amount116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;externalBeneficiaryId\&quot;:\&quot;{\\\&quot;externalBeneficiaryId116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;VectorSize\&quot;:\&quot;{\\\&quot;VectorSize116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;LTI_Amount\&quot;:\&quot;{\\\&quot;LTIAmount116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;ASTI_Payment_Method\&quot;:\&quot;{\\\&quot;ASTIPaymentMethod116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;ThirdPartyPayTo\&quot;:\&quot;{\\\&quot;ThirdPartyPayTo116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;externalBankCountry\&quot;:\&quot;{\\\&quot;externalCountry116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;externalPaymentScheme\&quot;:\&quot;{\\\&quot;PaymentScheme116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;ThirdPartyPayableAt\&quot;:\&quot;{\\\&quot;ThirdPartyPayableAt116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;FinalVector\&quot;:\&quot;{\\\&quot;disbursementDetails116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;Third__Party_Transfer\&quot;:\&quot;{\\\&quot;ThirdPartyTransfer116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;,\&quot;externalPaymentRef\&quot;:\&quot;{\\\&quot;paymentReference116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;},\&quot;serviceDisplayName\&quot;:\&quot;Disbursement Detail Validation\&quot;,\&quot;controlId\&quot;:\&quot;Delete_3116cd2a3fedd19FZ%28313\&quot;,\&quot;serviceName\&quot;:\&quot;UB_LEN_DisburseMentDetailValidationFatom_SRV\&quot;,\&quot;widgetType\&quot;:\&quot;DIALOG\&quot;,\&quot;currencyAssociation\&quot;:{\&quot;LoanAmount\&quot;:\&quot;LoanAmount_CurrCode\&quot;,\&quot;LTIAmount\&quot;:\&quot;LTIAmount_CurrCode\&quot;,\&quot;ASTIAmount\&quot;:\&quot;ASTIAmount_CurrCode\&quot;,\&quot;disbursementDetails\&quot;:\&quot;{aSTIAmount\\u003ddisbursementDetails#ISOCURRENCYCODE, sTIAmount\\u003ddisbursementDetails#ISOCURRENCYCODE, disbursementAmount\\u003ddisbursementDetails#ISOCURRENCYCODE, lTIAmount\\u003ddisbursementDetails#ISOCURRENCYCODE}\&quot;,\&quot;ThirdParty_Amount\&quot;:\&quot;ThirdParty_Amount_CurrCode\&quot;,\&quot;STIAmount\&quot;:\&quot;STIAmount_CurrCode\&quot;,\&quot;fixedInterestAmountPerDisb\&quot;:\&quot;fixedInterestAmountPerDisb_CurrCode\&quot;,\&quot;AmountOrPercentage\&quot;:\&quot;AmountOrPercentage_CurrCode\&quot;,\&quot;RemainingAmount\&quot;:\&quot;RemainingAmount_CurrCode\&quot;}}&quot;]});});</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Delete_3116cd2a3fedd19FZ%28313&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name=&quot;Delete&quot;]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='116cd2a3fedd19FZ%28313']/table/tbody/tr[30]/td[17]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='External Beneficiary Id'])[1]/following::input[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='External Payment Type'])[1]/following::input[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='yyyy-MM-dd'])[2]/preceding::input[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='yyyy-MM-dd'])[3]/preceding::input[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[17]/input</value>
   </webElementXpaths>
</WebElementEntity>
