<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Search</name>
   <tag></tag>
   <elementGuidId>20e37623-d6f0-4f0d-997a-efedec2b05d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Find_4116cd2a3fedd19FZ%28313']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uitype</name>
      <type>Main</type>
      <value>Button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Find_4116cd2a3fedd19FZ%28313</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dojo-props</name>
      <type>Main</type>
      <value>readOnly:false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>require([&quot;uxp/utility&quot;], function(utility){utility.displayTooltipMessage(&quot;Find_4116cd2a3fedd19FZ%28313&quot;);});</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>require([&quot;uxp/utility&quot;], function(utility){utility.toolTipHandling();});</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>require([&quot;uxp/events&quot;], function(events){events.eventsToInvoke({&quot;callService&quot;:[&quot;{\&quot;srcFormId\&quot;:\&quot;116cd2a3fedd19FZ%28313\&quot;,\&quot;requestMapping\&quot;:{\&quot;09IsLTIOnOsBalance\&quot;:\&quot;[\\\&quot;LTIonOsBalance116cd2a3fedd19FZ%28313\\\&quot;]\&quot;},\&quot;responseMapping\&quot;:{\&quot;PlanType\&quot;:\&quot;{\\\&quot;hiddenLabelLTIPlanType116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;,\\\&quot;LTIPlanType116cd2a3fedd19FZ%28313\\\&quot;:\\\&quot;\\\&quot;}\&quot;},\&quot;serviceDisplayName\&quot;:\&quot;Find Loan Insurance Plan Type\&quot;,\&quot;controlId\&quot;:\&quot;Find_4116cd2a3fedd19FZ%28313\&quot;,\&quot;serviceName\&quot;:\&quot;LEN_FindInsurancePlanType\&quot;,\&quot;currencyAssociation\&quot;:{\&quot;LoanAmount\&quot;:\&quot;LoanAmount_CurrCode\&quot;,\&quot;LTIAmount\&quot;:\&quot;LTIAmount_CurrCode\&quot;,\&quot;ASTIAmount\&quot;:\&quot;ASTIAmount_CurrCode\&quot;,\&quot;disbursementDetails\&quot;:\&quot;{aSTIAmount\\u003ddisbursementDetails#ISOCURRENCYCODE, sTIAmount\\u003ddisbursementDetails#ISOCURRENCYCODE, disbursementAmount\\u003ddisbursementDetails#ISOCURRENCYCODE, lTIAmount\\u003ddisbursementDetails#ISOCURRENCYCODE}\&quot;,\&quot;ThirdParty_Amount\&quot;:\&quot;ThirdParty_Amount_CurrCode\&quot;,\&quot;STIAmount\&quot;:\&quot;STIAmount_CurrCode\&quot;,\&quot;fixedInterestAmountPerDisb\&quot;:\&quot;fixedInterestAmountPerDisb_CurrCode\&quot;,\&quot;AmountOrPercentage\&quot;:\&quot;AmountOrPercentage_CurrCode\&quot;,\&quot;RemainingAmount\&quot;:\&quot;RemainingAmount_CurrCode\&quot;}}&quot;]});});</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Find_4116cd2a3fedd19FZ%28313&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Find_4116cd2a3fedd19FZ%28313']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='116cd2a3fedd19FZ%28313']/table/tbody/tr[21]/td[10]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LTI Plan Type'])[1]/following::input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STI Amount'])[1]/following::input[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASTI Payment Method'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LTI Amount'])[1]/preceding::input[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[21]/td[10]/input</value>
   </webElementXpaths>
</WebElementEntity>
