<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Paymentinternalreference</name>
   <tag></tag>
   <elementGuidId>0ec5a11f-e80e-4d32-bdf0-4835c88402f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,&quot;paymentReference&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,&quot;paymentReference&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
