<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Interestfrequency</name>
   <tag></tag>
   <elementGuidId>e5e75e12-4dc8-4ce1-b4c6-0d3a30f39d38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,&quot;InterestFrequency&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,&quot;InterestFrequency&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
