<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AutoPopulationMethod</name>
   <tag></tag>
   <elementGuidId>1753272f-a221-400d-be07-aebbab53efbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@id,&quot;AutoPopulationMethod&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@id,&quot;AutoPopulationMethod&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
